services/tasks/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: "tasks#index"
  get '/tasks', to: 'tasks#index'
  post '/', to: 'tasks#create'
  patch '/shuffle', to: 'tasks#shuffle'
  patch '/task/:id', to: 'tasks#complete'
  get '/login', to: 'tasks#login'
  get '/tasks/resend_all_tasks',
      to: 'tasks#resend_all_tasks',
      as: :resend_data
end

services/tasks/app/models/task.rb
# frozen_string_literal: true

# a Task
class Task < ApplicationRecord
  enum status: { open: 0, complete: 1 }

  belongs_to :user

  validates :description, presence: true
  validates :status, presence: true
  validates :description, format: { without: /\[.+\]/ }

  alias_attribute :assignee, :user
end

# == Schema Information
#
# Table name: tasks
#
#  id           :uuid             not null, primary key
#  description  :string           not null
#  user_id      :uuid
#  status       :integer          default("open")
#  completed_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  jira_id      :string
#

services/tasks/app/models/user.rb
# frozen_string_literal: true

# a User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[aa_auth]
  enum status: { deactivated: 0, active: 1 }

  has_and_belongs_to_many :roles
  has_many :tasks

  def permissions
    return [] unless roles

    roles.includes(:permissions).map(&:permissions).flatten.uniq
  end
end

# == Schema Information
#
# Table name: users
#
#  id         :uuid             not null, primary key
#  user_idx   :uuid             not null
#  name       :string
#  status     :integer          default("active")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

services/tasks/app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController

  class MessageWasNotPublished < StandardError; end

  # 'aa' stands for 'Async Architecture' course name
  TASKS_TOPIC_CUD = 'aa_tasks_stream'
  TASKS_TOPIC_BE = 'aa_tasks_lifecycle'

  before_action :authenticate_user!, except: :login
  before_action do
    if current_user
      current_user_roles
      current_user_permissions
    end
  end

  def login; end

  def index
    @tasks = Task.includes(:user).where(status: :open).order(:created_at).all
  end

  def create
    return unless @permissions.include? 'add_new_task'

    @new_task = Task.new(jira_id: params['jira_id'],
                         description: params['description'],
                         user: random_popug)

    if @new_task.save
      publish_TaskUpdated_message(@new_task)

      message = {
        event_name: 'TaskCreated',
        message_version: 2,
        message_time: Time.now,
        producer: 'task_service',
        data: {
          task_public_id: @new_task.id,
          assignee_public_id: @new_task.assignee.user_idx,
          timestamp: Time.now.utc
        }
      }
      publish_BE_message(message)

      redirect_to action: 'index'
    else
      redirect_to root_path, alert: 'Error'
    end
  end

  def shuffle
    return unless @permissions.include? 'shuffle_open_tasks'

    messages = []
    open_tasks = Task.where(status: :open)
    ApplicationRecord.transaction do
      open_tasks.each do |task|
        current_assignee_id = task.user_id # id only to avoid extra db hit
        new_assignee = random_popug

        next if current_assignee_id == new_assignee.id

        task.assignee = new_assignee
        task.save

        messages << {
          event_name: 'TaskAssigned',
          message_version: 2,
          message_time: Time.now,
          producer: 'task_service',
          data: {
            task_public_id: task.id,
            assignee_public_id: task.assignee.user_idx,
            timestamp: Time.now.utc
          }
        }
      end
    end

    open_tasks.each { |task| publish_TaskUpdated_message(task) }
    messages.each { |message| publish_BE_message(message) }

    redirect_to action: 'index'
  end

  def complete
    task = Task.find(params[:id])
    return unless (@permissions.include? 'complete_own_tasks' and task.assignee == current_user) or
      @permissions.include? 'complete_all_tasks'

    task.status = :complete
    task.completed_at = Time.now.utc
    task.save!

    message = {
      event_name: 'TaskCompleted',
      message_version: 2,
      message_time: Time.now,
      producer: 'task_service',
      data: {
        task_public_id: task.id,
        assignee_public_id: task.assignee.user_idx,
        completed_by_public_id: current_user.user_idx, # i.e. can be closed by admin
        timestamp: task.completed_at
      }
    }
    publish_TaskUpdated_message(task)
    publish_BE_message(message)
    redirect_to action: 'index'
  end

  def resend_all_tasks
    count = 0
    Task.includes(:user).all.each do |task|
      count += 1
      publish_TaskUpdated_message(task)
    end

    redirect_to root_path, notice: "Information about #{count} task(s) was resent."
  end

  private

  def publish_TaskUpdated_message(task)
    message = {
      event_name: 'TaskUpdated',
      message_version: 2,
      message_time: Time.now,
      producer: 'task_service',
      data: {
        task_public_id: task.id,
        jira_id: task.jira_id,
        description: task.description,
        assignee_public_id: task.assignee.user_idx,
        status: task.status,
        timestamp: task.completed_at
      }
    }

    begin
      SchemaValidator.new(message, :TaskUpdated_v2).validate!
      Producer.new.publish(message, topic: TASKS_TOPIC_CUD)
    rescue
      logger.warn "Error occurred when publishing tasks CUD message"
      logger.warn message
      logger.warn [MessageWasNotPublished, $!.to_s, $!.backtrace]
    end
  end

  def publish_BE_message(message)
    begin
      SchemaValidator.new(message, :TaskCreated_v2).validate!
      Producer.new.publish(message, topic: TASKS_TOPIC_BE)
    rescue
      logger.warn "Error occurred when publishing tasks BE"
      logger.warn message
      logger.warn [MessageWasNotPublished, $!.to_s, $!.backtrace]
    end
  end

  def random_popug
    @workers ||= User.joins(:roles)
                     .where('roles.name': 'worker')
                     .all
    @workers.sample
  end

  def current_user_roles
    @roles ||= current_user.roles.pluck(:name)
  end

  def current_user_permissions
    @permissions ||= current_user.permissions.pluck(:name)
  end
end

services/tasks/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: %i[aa_auth]

  def aa_auth
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    user_idx = request.env['omniauth.auth']['info']['id']
    @user = User.find_by(user_idx: user_idx)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'aa_auth') if is_navigational_format?
    else
      session['devise.oauth2_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

services/tasks/app/helpers/sessions_helper.rb
module SessionsHelper
end

services/tasks/app/views/common/_logout_btn.html.erb
<form data-turbo="true" action="<%= destroy_user_session_path %>" accept-charset="UTF-8" method="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <button class="btn btn-secondary btn-sm" type='submit'>Sign out</button>
</form>

services/tasks/app/views/common/_user_info.html.erb
<div class="container">
  <div>Hello <%= current_user.name %>!<br/>
    Your roles: <%= @roles.join(', ') %>.<br/>
    Your permissions: <%= @permissions.join(', ') %>.<br/>
    <%= render template: 'common/_logout_btn' %></div>
</div>

services/tasks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <title>Tasks</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="container-fluid">
  <div class="container py-md-3">
    <div class="row">
      <div class="col">
        <% if notice %><div class="alert alert-success" role="alert"><%= notice %></div><% end %>
        <% if alert %><div class="alert alert-warning" role="alert"><%= alert %></div><% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

services/tasks/app/views/tasks/index.html.erb
<div class="container">
  <h1>Popug Tasks Tracker</h1>
  <a class="btn btn-outline-warning" href="<%= resend_data_path %>" role="button">Resend data</a>
</div>
<%= render template: 'common/_user_info' %>
<div name="managementActions" class="container">
  <% if @permissions.include? 'add_new_task' %>
    <h2>For management</h2>
    <%= form_with model: @new_task do |form| %>
      <div class="mb-3">
        <div class="input-group">
          <span class="input-group-btn">
            <button class="btn btn-warning" type="submit">Add new task</button>
          </span>
          <input class="form-control" type="text" placeholder="Jira ID" name="<%= :jira_id %>" id="<%= :jira_id %>">
          <input class="form-control" type="text" placeholder="Task description" name="<%= :description %>" id="<%= :description %>">
        </div>
      </div>
    <% end %>
  <% end %>
  <% if @permissions.include? 'shuffle_open_tasks' %>
    <div class="mb-3">
      <a data-turbo-method="patch" class="btn btn-primary" href="<%= shuffle_path %>" role="button">Shuffle</a>
    </div>
  <% end %>
</div>
<div name="viewer" class="container">
  <h1>Open Tasks</h1>
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Jira ID</th>
      <th scope="col">Task Description</th>
      <th scope="col">Assignee</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @tasks.each_with_index do |task, i| %>
      <% if (@permissions.include? 'view_own_tasks' and task.assignee == current_user) or @permissions.include? 'view_all_tasks' %>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <td><%= task.jira_id %></td>
          <td><%= task.description %></td>
          <td><%= task.assignee.name %></td>
          <td>
            <% if (@permissions.include? 'complete_own_tasks' and task.assignee == current_user) or @permissions.include? 'complete_all_tasks' %>
              <%= link_to "Complete", "/task/#{task.id}", data: { turbo_method: :patch } %>
            <% else %>
              Just watch
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>