services/accounting/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: 'accounting#index'
  get '/login', to: 'accounting#login', as: :login

  get '/accounting', to: 'accounting#index'
  get '/analytics', to: 'analytics#index'
  get '/accounting/calc_and_make_payment',
      to: 'accounting#calc_and_make_payment',
      as: :calc_payment
  patch '/analytics/recalc_users_balances',
        to: 'analytics#recalc_users_balances',
        as: :recalc_balances
end

services/accounting/app/controllers/accounting_controller.rb
# frozen_string_literal: true

class AccountingController < ApplicationController
  # 'aa' stands for 'Async Architecture' course name
  ACCOUNTING_TOPIC_BE = 'aa_accounting_lifecycle'

  before_action :authenticate_user!, except: :login
  before_action do
    if current_user
      current_user_roles
      current_user_permissions
    end
  end

  def login; end

  def index
    if @current_user_permissions.include? 'view_worker_stats'
      @records = TransactionLogRecord.includes(:task)
                                     .where(user_id: current_user.id)
                                     .order(record_time: :desc)
                                     .all
      @balance = current_user.balance
      @payments = @records.where(record_type: :payment)
      @last_payment = -(@payments.first&.amount or 0)
    end
    if @current_user_permissions.include? 'view_management_stats'
      @last_payment_time = TransactionLogRecord.order(record_time: :desc)
                                               .where(record_type: :payment)
                                               .first&.record_time
      @management_records = TransactionLogRecord.includes(:task, :user)
                                                .where('record_time > ?', @last_payment_time)
                                                .order(record_time: :desc)
                                                .all
      @earned_today = -@management_records.pluck(:amount).sum
    end
  end

  def calc_and_make_payment
    Producer.new.publish({ command: :start }, topic: ACCOUNTING_TOPIC_BE)

    redirect_to root_path, notice: 'Payment process started'
  end
end

services/accounting/app/views/accounting/index.html.erb
<div class="container">
  <h1>Accounting</h1>
  <a class="btn btn-outline-primary" href="<%= analytics_path %>" role="button">Analytics</a>
  <a class="btn btn-outline-warning" href="<%= calc_payment_path %>" role="button">Close day, calc and make payments</a>
</div>
<%= render template: 'common/_user_info' %>
<% if @current_user_permissions.include? 'view_management_stats' %>
  <div class="container">
    <h1>Management stats</h1>
    <h3>As for now, management balance is <%= @earned_today %>.<br/> Last payment was <%= @last_payment_time %>.</h3>
    <h2>Audit log</h2>
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Record time</th>
        <th scope="col">Event time</th>
        <th scope="col">Jira ID</th>
        <th scope="col">Task description</th>
        <th scope="col">Amount</th>
        <th scope="col">Assignee</th>
        <th scope="col">Note</th>
      </tr>
      </thead>
      <tbody>
      <% @management_records.each_with_index do |record, i| %>
        <tr>
          <th scope="row"><%= i+1 %></th>
          <td><%= record.record_time %></td>
          <td><%= record.event_time %></td>
          <td><%= record&.task&.jira_id %></td>
          <td><%= record&.task&.description %></td>
          <td><%= -record.amount %></td>
          <td><%= record.user.name %></td>
          <td><%= record.note %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<% if @current_user_permissions.include? 'view_worker_stats' %>
  <div class="container">
    <h1>Worker stats</h1>
    <h2>Your balance is <%= @balance %></h2>
    <h2>Your last payment was <%= @last_payment %></h2>
    <h2>Audit log</h2>
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Record time</th>
        <th scope="col">Event time</th>
        <th scope="col">Task description</th>
        <th scope="col">Amount</th>
        <th scope="col">Note</th>
      </tr>
      </thead>
      <tbody>
      <% @records.each_with_index do |record, i| %>
          <tr>
            <th scope="row"><%= i+1 %></th>
            <td><%= record.record_time %></td>
            <td><%= record.event_time %></td>
            <td><%= record&.task&.description %></td>
            <td><%= record.amount %></td>
            <td><%= record.note %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

services/accounting/app/views/accounting/login.html.erb
<div class="container-sm">
  <h1>Please log in</h1>
  <form data-turbo="false" action="<%= user_aa_auth_omniauth_authorize_path %>" accept-charset="UTF-8" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <button class="btn btn-primary btn-lg" type='submit'>Login at Popug Auth</button>
  </form>
</div>