services/accounting/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: 'accounting#index'
  get '/login', to: 'accounting#login', as: :login

  get '/accounting', to: 'accounting#index'
  get '/analytics', to: 'analytics#index'
  get '/accounting/calc_and_make_payment',
      to: 'accounting#calc_and_make_payment',
      as: :calc_payment
  patch '/analytics/recalc_users_balances',
        to: 'analytics#recalc_users_balances',
        as: :recalc_balances
end

services/accounting/app/controllers/analytics_controller.rb
# frozen_string_literal: true

class AnalyticsController < ApplicationController

  before_action :authenticate_user!, except: :login
  before_action do
    @page_title = 'Analytics'
    if current_user
      current_user_roles
      current_user_permissions
    end
    unless current_user_roles.include? 'admin'
      redirect_to login_path, alert: 'Only admins can see analytics'
    end
  end

  def login
    redirect_to login_path
  end

  def index
    @last_payment_time = TransactionLogRecord.order(record_time: :desc)
                                             .where(record_type: :payment)
                                             .first&.record_time
    @management_records = TransactionLogRecord.includes(:task, :user)
                                              .where('record_time > ?', @last_payment_time)
                                              .order(record_time: :desc)
                                              .all
    @earned_today = -@management_records.pluck(:amount).sum

    @poor_workers = User.joins(:roles).where('roles.name': 'worker').where('balance < ?', 0).all

    periods = [1, 7, 30]
    tasks = Task.where(status: :complete)
                .where('completed_at > ?', Time.now - periods.max.hours)
                .all
    last_period = 0
    @most_payed_tasks_per_period = periods.map do |period|
      task = tasks.where('completed_at > ?', Time.now - period.hours)
                  .where('completed_at < ?', Time.now - last_period.hours)
                  .order(reward: :desc)
                  .first
      last_period = period
      [period, task&.reward, task&.description, task&.completed_at]
    end
  end

  def recalc_users_balances
    @records = TransactionLogRecord.all
    count = 0
    ActiveRecord::Base.transaction do
      User.where(status: :active).each do |user|
        true_balance = @records.where(user: user).pluck(:amount).sum
        next if user.balance == true_balance

        user.update(balance: true_balance)
        count += 1
      end
    end

    redirect_to analytics_path, notice: "Updated for #{count} users"
  end
end

services/accounting/app/views/analytics/index.html.erb
<div class="container">
  <h1>Analytics</h1>
  <a class="btn btn-outline-primary" href="<%= accounting_path %>" role="button">Accounting</a>
  <a data-turbo-method="patch"class="btn btn-outline-primary" href="<%= recalc_balances_path %>" role="button">Recalc balances</a>
</div>
<%= render template: 'common/_user_info' %>
<div class="container">
  <h1>Management stats</h1>
  <h3>As for now, management balance is <%= @earned_today %>.<br/> Last payment was <%= @last_payment_time %>.</h3>
  <h1>Poor Workers</h1>
  <ul class="list-group">
    <% @poor_workers.each do |worker| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= worker.name %>
        <span class="badge bg-success rounded-pill"><%= worker.balance %></span>
      </li>
    <% end %>
  </ul>
  <h1>Most payed tasks</h1>
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Period in hours</th>
      <th scope="col">Cost</th>
      <th scope="col">Description</th>
      <th scope="col">Completed_at</th>
    </tr>
    </thead>
    <tbody>
    <% @most_payed_tasks_per_period.each do |period, reward, description, completed_at| %>
      <tr>
        <td><%= period%></td>
        <td><%= reward %></td>
        <td><%= description %></td>
        <td><%= completed_at&.in_time_zone('Asia/Sakhalin') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>